------------------------------------------------------------------------

## Simple Linear Regressions

```{r echo = TRUE}
library(Fgmutils)
data <- read.csv("https://gattonweb.uky.edu/sheather/book/docs/datasets/playbill.csv")
x <- data$LastWeek
y <- data$CurrentWeek
plot(x,y)
xm = mean(x)
ym = mean(y)
SXX = sum((x-xm)^2)
SXY = sum((x-xm)*(y-ym))
s1 = SXY/SXX
s0 = ym - xm*s1
r = (y -s0 - s1*x)
RSS = sum(r^2)
S = sqrt(RSS/(length(x)-2))
se = S/sqrt(SXX)
q = qt(0.975,length(x)-2)
print (s1)
print (s1-(q*se))
print (s1+(q*se))
l = (1/length(x))+(xm^2)/(SXX)
se1 = S*sqrt(l)
t = (s0 - 10000)/se1
p = 2*pt(q=t, df=length(x)-2, lower.tail=FALSE)
l1 = (1 + (1/length(x)) + ((400000-xm)^2)/SXX)
al = q*S*sqrt(l1)
print (s0+s1*400000)
print (s0+s1*400000 - al)
print (s0+s1*400000 + al)
```

```{r echo = TRUE}
library(Fgmutils)
x <- X1$LoanPaymentsOverdue
y <- X1$PriceChange
plot(x,y)
n <- length(x)
xm <- mean(x)
ym <- mean(y)
SXX <- sum((x-xm)^2)
SXY <- sum((x-xm)*(y-ym))
b1 <- SXY/SXX
b0 <- ym - xm*b1
q <- qt(0.975,n-2)
r <- (y)- (b1*x) - (b0)
RSS <- sum(r*r)
S <- sqrt(RSS/(n-2))
se <- S/sqrt(SXX)
print (b1)
print (b1-q*se)
print (b1+q*se)
se1 <- sqrt((1/n) + (((4-xm)^2)/(SXX)))
print (b0 + b1*4)
print (b0 + b1*4 - se1*S*q)
print (b0 + b1*4 + se1*S*q)
```

```{library(Fgmutils)}
X3 <- read.delim("https://gattonweb.uky.edu/sheather/book/docs/datasets/invoices.txt")
x <- X3$Invoices
y <- X3$Time
n <- length(x)
xm <- mean(x)
ym <- mean(y)
SXX <- sum((x-xm)^2)
SXY <- sum((x-xm)*(y-ym))
b1 <- SXY/SXX
b0 <- ym - xm*b1
r <- (y - xm*b1 - b0)
RSS <- sum(r*r)
S <- sqrt(RSS^2)/(n-2)
l <- sqrt((1/n)+(xm*xm)/(SXX))
q <- qt(0.975,n-2)
print (b1)
print (b1-(S*l*q))
print (b1+(S*l*q))
l1 <- sqrt((1)+(1/n)+(((130-xm)^2)/SXX))
print (b1*130 + b0 - S*q*l1)
print (b1*130 + b0)
print (b1*130 + b0 + S*q*l1)
se1 <- S/sqrt(SXX)
t <- (b1-0.01)/(se1)
p = 2*pt(q=t, df=length(x)-2, lower.tail=FALSE)
print (p)
```
